### ISSUE TITLE
Community flagged videos coming back as 410

### ISSUE THREAD

**Issue by Bullfrog098** [fent/node-ytdl-core#1009]
Trying to download a video that is flagged inappropriate or offensive (Ex. https://www.youtube.com/watch?v=hc0ZDaAZQT0) comes back as a 410. This was fixed in youtube-dl with "&bpctr=9999999999" so all that needs to be done is when the base_url and id are added together add "&bpctr=9999999999" right after.

**Comment by redbrain** [comment]
Thanks for the information! Do you have time to draft a PR to close the issue?

**Comment by Bullfrog098** [comment]
Not sure if it needs to be placed elsewhere but its in #1010

**Comment by MIGI10** [comment]
Adding that to the url doesn't fix the 410 errors for me... I have tried that together with passing a cookie and an identity token header but the errors persist. I'm able to download age restricted videos but not those flagged as sensitive content (like the one linked above)

**Comment by Bullfrog098** [comment]
> Adding that to the url doesn't fix the 410 errors for me... 
sorry for late response but did you add "&bpctr=9999999999" into the ytdls code itself or did you just add it into the url you were requesting?

**Comment by TimeForANinja** [comment]
should be fixed by #1022

**Comment by cchen028** [comment]
still experiencing the issue on certain videos after updating to 4.9.2

**Comment by TimeForANinja** [comment]
same, but #1010 is not fixing it for me 🤔

**Comment by FadelesSpade** [comment]
This issue is still arising for all age restricted videos on 4.10.0 and #1010 is not fixing it either.

**Comment by codeerror90** [comment]
can't fix it for me

**Comment by pixelblob** [comment]
Any updates on this?

**Comment by aliazhar-id** [comment]
Nothing, I'm still getting this problem, sad

**Comment by TimeForANinja** [comment]
> Nothing, I'm still getting this problem, sad

you can try the #1080 and tell me if that fixed it for you 🧐

**Comment by AntonyOnScript** [comment]
same issue here

**Comment by umarengr99** [comment]
i m using ytdl-core npm package and facing Region Restriction error: which throw a generic Status code 410. 
how i can fix this issue by changing the region.
