### ISSUE TITLE
[Electron Bug] setTimeout().unref() is undefiend

### ISSUE THREAD

**Issue by youkaclub** [fent/node-ytdl-core#829]
Thank you for the wonderful library.

Please remove `.unref()` from https://github.com/fent/node-ytdl-core/blob/6d2b64e37127d956a4761c4cfc483ea72630cda4/lib/cache.js#L14 to make it work for electron users.

**Comment by PrestonN** [comment]
I've already pushed a fix for this with #823. The fix will be in the next release if I had to guess.

**Comment by youkaclub** [comment]
I’ve double checked and the unref call is still exists in your code

**Comment by PrestonN** [comment]
I'm well aware. If you look at the linked issue in that PR, you'll notice that there are methods that can be added to the code to allow `unref` to be included in the module. I've already tested this change in my own Electron app and the included change allows `unref` to stay.

**Comment by fent** [comment]
sorry forgot to push a release yesterday. will do so in a min

**Comment by fent** [comment]
v4.1.6 is out

**Comment by youkaclub** [comment]
Thanks 👍
